import baseConfig from "../../eslint.config.mjs";

export default [
    ...baseConfig,
    // Generated by `prisma generate` (git-ignored).
    { ignores: ["src/generated/**"] },
    // CLI scripts (seeds) report progress on the terminal; the app itself logs through PinoLogger.
    { files: ["prisma/**/*.ts"], rules: { "no-console": "off" } },
];
