import baseConfig from "../../eslint.config.mjs";

/**
 * `prisma.unscoped()` bypasses tenant isolation (D-018/D-080). Allowed only for migrations, seeds, signup/login before an
 * office is known, and platform-admin code, and every call must say why in a comment directly above it (or on the same
 * line): `// unscoped: <reason>`. Reviewers grep for `unscoped:`.
 */
const unscopedNeedsReason = {
  meta: { type: "problem", schema: [], messages: { missing: "prisma.unscoped() bypasses tenant isolation: add `// unscoped: <reason>` directly above this call." } },
  create(context) {
    const source = context.sourceCode;
    const check = (node) => {
      const line = node.loc.start.line;
      const justified = source
        .getAllComments()
        .some((comment) => (comment.loc.end.line === line - 1 || comment.loc.start.line === line) && /unscoped:\s*\S/.test(comment.value));
      if (!justified) context.report({ node, messageId: "missing" });
    };
    // Any access, not only a direct call: `x.unscoped()`, `x['unscoped']`, `x.unscoped.call(x)`, `const { unscoped } = x`.
    return {
      "MemberExpression[computed=false][property.name='unscoped']": check,
      "MemberExpression[computed=true][property.value='unscoped']": check,
      "ObjectPattern > Property[key.name='unscoped']": check,
    };
  },
};

export default [
    ...baseConfig,
    // Generated by `prisma generate` (git-ignored).
    { ignores: ["src/generated/**"] },
    {
        files: ["**/*.ts"],
        plugins: { nexlegtiq: { rules: { "unscoped-needs-reason": unscopedNeedsReason } } },
        rules: {
            // error, not warn: CI does not fail on warnings. The `// unscoped: <reason>` comment is how a call is allowed.
            "nexlegtiq/unscoped-needs-reason": "error",
            // String-built SQL is never allowed (CLAUDE.md non-negotiable 9); tagged $queryRaw/$executeRaw only.
            "no-restricted-properties": [
                "error",
                { property: "$queryRawUnsafe", message: "Use the tagged $queryRaw template (parameterised); tenant tables need officeId as a parameter." },
                { property: "$executeRawUnsafe", message: "Use the tagged $executeRaw template (parameterised); tenant tables need officeId as a parameter." },
            ],
        },
    },
    // Tests set up fixtures across offices on purpose.
    { files: ["**/*.spec.ts"], rules: { "nexlegtiq/unscoped-needs-reason": "off" } },
    // CLI scripts (seeds) report progress on the terminal; the app itself logs through PinoLogger.
    { files: ["prisma/**/*.ts"], rules: { "no-console": "off" } },
];
